/* Run before uploading the site. No dependencies; content hashes version the cache. */
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const root = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const urls = new Set(['./index.html', './toeic.html', './coding.html', './assets/toeic.css?v=20260915-1', './assets/toeic.js?v=20260915-1', './assets/coding.css?v=20260915-2', './assets/coding.js?v=20260915-2', './manifest.webmanifest', './data/study-details.js?v=20260929-2']);
for (const match of html.matchAll(/(?:src|href)="((?:assets|data)\/[^"#]+)"/g)) urls.add('./' + match[1]);
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'manifest.webmanifest'), 'utf8'));
manifest.icons.forEach(icon => urls.add('./' + icon.src));
const assets = [...urls].sort();
const hash = crypto.createHash('sha256');
for (const url of assets) {
  hash.update(url);
  hash.update(fs.readFileSync(path.join(root, url.split('?')[0])));
}
hash.update(fs.readFileSync(path.join(root, 'sw.js')));
const data = {version: hash.digest('hex').slice(0, 16), assets};
fs.writeFileSync(path.join(root, 'pwa-assets.js'), '// Generated by node scripts/build-pwa.js\nself.SAA_PRECACHE = ' + JSON.stringify(data, null, 2) + ';\n');
console.log(`PWA: ${assets.length} assets, version ${data.version}`);
